### ISSUE TITLE
xclip: Can't open display: localhost:10.0

### ISSUE THREAD

**Issue by rdd2** [xxh/xxh#101]
Let me get something out of the way: Thank you all for this amazing piece of software. I have to work on many different servers every day and xxh saves me so many keystrokes. 

Now on to my question: I have this in my ```~/.ssh/config```
```
ForwardX11              yes
```
and xclip works when I ```ssh``` in. When ```xxh```-ing in, xclip complains:
```
root@hostname ~# echo "test2" | xclip
Error: Can't open display: localhost:10.0
```
It also works with local /bin/fish. Is there any other place where I have to configure the forwarding?

I'd be grateful for any pointers.

**Comment by anki-code** [comment]
Hi @rdd2 ! Glad to rad that xxh works for you!

I can reproduce. Good catch!
I have a quick try and found that if we change a HOME directory the xclip is not working:
```bash
ssh -X host
echo 1 | xclip
# it works
HOME=/tmp
echo 1 | xclip
# Error: Can't open display: localhost:10.0
```
Next I've found that there is `.Xauthority` file that ssh created in home directory (`/home/user`). Because after connection `HOME` becomes `XXH_HOME`  then this file is missing.

The manual fix is:
```bash
xxh host
ln -s /home/$USER/.Xauthority
echo 'enjoy :)' | xclip
```

**Comment by rdd2** [comment]
Thank you for your help. I have made a PR: https://github.com/xxh/xxh-shell-fish/pull/11

**Comment by rdd2** [comment]
#[](url)
